#服务端口
server:
  port: 8059
  
spring:
  data:
    mongodb:
      uri: mongodb://antBizCommon:antBizFactCommon@172.19.104.102:27031,172.19.104.127:27031,172.19.104.104:27031/business_common
      
token.validate.service.url: 'https://antfact.com/auth2/authz/validate'